[versions]
kotlin = "2.3.10"
kotlinxCoroutines = "1.10.2"
kotlinxSerialization = "1.11.0"
shadow = "9.4.1"
hytale = "2026.01.17"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinxSerializationCbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "kotlinxSerialization" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
hytaleServer = { module = "com.hypixel.hytale:HytaleServer-parent", version.ref = "hytale" }

[bundles]
kotlinxEcosystem = ["kotlinxSerializationJson", "kotlinxSerializationCbor", "kotlinxCoroutines", "kotlinReflect"]

[plugins]
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }